name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Set Git Config
        run: |
          git config --global user.email 'github-actions@github.com'
          git config --global user.name 'github-actions'
          git remote set-url origin https://${{ secrets.GH_PAT }}@github.com/Rajesh-Khanna/non-standard-units.git
        
      - name: Build and Deploy
        run: |
          echo "CONFIG setup done"
          npm run deploy
